### ISSUE TITLE
Update for new items

### ISSUE THREAD

**Issue by xDeeKay** [koenbollen/vampire-survivors-tips#3]
I love this widget, especially the pop-out feature. Really useful.
Any chance this can be updated to include the new items?

**Comment by koenbollen** [comment]
I can see if more items will fit. I'm only not really playing the game anymore.. Can you tell me which are the new items and how they are evolved?

**Comment by xDeeKay** [comment]
Certainly, here are the new evolutions:

Pentagram with Crown gives you Gorgeous Moon
Gatti Amari with Stone Mask gives you Vicious Hunger
Song of Mana with Skull O'Maniac gives you Mannajja
Shadow Pinion with Wings gives you Valkyrie Turner
Clock Lancet with Silver Ring and Gold Ring gives you Infinite Corridor
Laurel with Metaglio Left and Metaglio Right gives you Crimson Shroud

**Comment by koenbollen** [comment]
I've added the items you've listed (took me a while to find the correct images for it. 😁).
Should go live to https://vampire-survivors-tips.netlify.app/ automatically in a bit.

**Comment by xDeeKay** [comment]
You're a legend! Thank you
